// <auto-generated />
using System;
using CadeirasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadeirasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CadeirasAPI.Models.AlocacaoModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("cadeira_id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("data_hora_fim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_hora_init")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("cadeira_id");

                    b.ToTable("Alocacao");
                });

            modelBuilder.Entity("CadeirasAPI.Models.CadeiraModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Cadeira");
                });

            modelBuilder.Entity("CadeirasAPI.Models.AlocacaoModel", b =>
                {
                    b.HasOne("CadeirasAPI.Models.CadeiraModel", "Cadeira")
                        .WithMany()
                        .HasForeignKey("cadeira_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadeira");
                });
#pragma warning restore 612, 618
        }
    }
}
